const std = @import("std");
const ashet = @import("ashet");

const Color = ashet.abi.Color;
const Size = ashet.abi.Size;

const parse = ashet.graphics.embed_comptime_bitmap;

const icon_palette = .{
    .F = Color.white,
    .B = Color.from_rgb(0xa6, 0xcf, 0xd0),
    .@"9" = Color.from_rgb(0x50, 0x5d, 0x6d),
    .@"4" = Color.from_rgb(0xe4, 0x16, 0x2b),
};

pub const maximize = parse(icon_palette,
    \\.........
    \\.FFFFFFF.
    \\.F.....F.
    \\.FFFFFFF.
    \\.F.....F.
    \\.F.....F.
    \\.F.....F.
    \\.FFFFFFF.
    \\.........
);

pub const minimize = parse(icon_palette,
    \\.........
    \\.........
    \\.........
    \\.........
    \\.........
    \\.........
    \\.........
    \\..FFFFF..
    \\.........
);

pub const restore = parse(icon_palette,
    \\.........
    \\...FFFFF.
    \\...F...F.
    \\.FFFFF.F.
    \\.FFFFF.F.
    \\.F...FFF.
    \\.F...F...
    \\.FFFFF...
    \\.........
);

pub const restore_from_tray = parse(icon_palette,
    \\.........
    \\..FFFFF..
    \\.........
    \\.........
    \\.........
    \\.........
    \\.........
    \\.........
    \\.........
);

pub const close = parse(icon_palette,
    \\444444444
    \\444444444
    \\44F444F44
    \\444F4F444
    \\4444F4444
    \\444F4F444
    \\44F444F44
    \\444444444
    \\444444444
);

pub const resize = parse(icon_palette,
    \\.........
    \\.FFF.....
    \\.F.F.....
    \\.FFFFFFF.
    \\...F...F.
    \\...F...F.
    \\...F...F.
    \\...FFFFF.
    \\.........
);

pub const cursor = parse(icon_palette,
    \\BBB..........
    \\9FFBB........
    \\9FFFFBB......
    \\.9FFFFFBB....
    \\.9FFFFFFFBB..
    \\..9FFFFFFFFB.
    \\..9FFFFFFFB..
    \\...9FFFFFB...
    \\...9FFFFFB...
    \\....9FF99FB..
    \\....9F9..9FB.
    \\.....9....9FB
    \\...........9.
);
