const std = @import("std");
const model = @import("widget-def-model");

const Allocator = std.mem.Allocator;

pub fn main() !u8 {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();

    const allocator = arena.allocator();
    const args = try std.process.argsAlloc(allocator);

    if (args.len != 3) return usage();

    const input_path = args[1];
    const output_path = args[2];

    const source = try std.fs.cwd().readFileAlloc(allocator, input_path, 1 * 1024 * 1024);
    const parsed = try model.from_json_str(allocator, source);

    var output_file = try std.fs.cwd().createFile(output_path, .{});
    defer output_file.close();

    var output_buffer: [4096]u8 = undefined;
    var output_writer = output_file.writer(&output_buffer);

    try renderDocument(allocator, &output_writer.interface, parsed.value);
    try output_writer.interface.flush();
    return 0;
}

fn usage() u8 {
    std.log.err("usage: gen-widget-types <input.json> <output.zig>", .{});
    return 1;
}

fn renderDocument(allocator: Allocator, writer: *std.Io.Writer, document: model.Document) !void {
    try writer.writeAll(
        \\// Generated by gen-widget-types.
        \\const std = @import("std");
        \\const ashet = @import("ashet");
        \\
        \\const UUID = ashet.gui.UUID;
        \\const ControlMessage = ashet.gui.ControlMessage;
        \\const NotifyEvent = ashet.gui.NotifyEvent;
        \\const Window = ashet.gui.Window;
        \\const Widget = ashet.gui.Widget;
        \\const Rectangle = ashet.abi.Rectangle;
        \\const Framebuffer = ashet.abi.Framebuffer;
        \\
        \\const usize_from_type = ashet.gui.usize_from_type;
        \\const type_from_usize = ashet.gui.type_from_usize;
        \\
        \\
    );

    for (document.widgets, 0..) |widget, index| {
        if (index != 0) {
            try writer.writeAll("\n\n");
        }
        try renderWidget(allocator, writer, document, widget);
    }

    if (document.types.len != 0) {
        for (document.types) |type_decl| {
            try writer.writeAll("\n");
            try renderTypeDeclaration(writer, type_decl);
        }
    }
}

fn renderWidget(allocator: Allocator, writer: *std.Io.Writer, document: model.Document, widget: model.Widget) !void {
    try writeDocComments(writer, "", widget.docs);
    try writer.print("pub const {s} = opaque {{\n", .{widget.name});
    try writer.print("    pub const uuid = UUID.constant(\"{s}\");\n", .{widget.uuid});

    if (widget.controls.len != 0) {
        try writer.writeAll("\n");
        for (widget.controls) |control| {
            try writer.print(
                "    pub const {s}_msg: ControlMessage = .from_int({d});\n",
                .{ control.name, control.identifier },
            );
        }
    }

    if (widget.events.len != 0) {
        try writer.writeAll("\n");
        for (widget.events, 0..) |event, index| {
            try writeDocComments(writer, "    ", event.docs);
            try writer.print(
                "    pub const {s}: NotifyEvent = .from_int({d});\n",
                .{ event.name, event.identifier },
            );
            if (index + 1 != widget.events.len) {
                try writer.writeAll("\n");
            }
        }
    }

    if (widget.types.len != 0) {
        try writer.writeAll("\n");
        for (widget.types, 0..) |type_decl, index| {
            if (index != 0) {
                try writer.writeAll("\n");
            }
            try renderTypeDeclaration(writer, type_decl);
        }
    }

    try writer.writeAll("\n\n");
    try renderCommonMethods(writer, widget.name);

    for (widget.controls) |control| {
        try writer.writeAll("\n");
        try renderControlMethod(allocator, writer, document, widget, control);
    }

    try writer.writeAll("\n\n");

    try writer.print(
        \\pub fn format(widget: *{[0]f}, w: *std.Io.Writer) !void {{
        \\    _ = widget;
        \\    try w.print("{[1]f}({{*}})", .{{w}});
        \\}}
        \\
    , .{
        std.zig.fmtId(widget.name),
        std.zig.fmtString(widget.name),
    });

    try writer.writeAll("\n};\n");
}

fn renderTypeDeclaration(writer: *std.Io.Writer, type_decl: model.TypeDeclaration) !void {
    var lines = std.mem.splitScalar(u8, type_decl.zig_type, '\n');
    const first_line = lines.first();

    try writer.print("    pub const {s} = {s}", .{ type_decl.name, first_line });
    while (lines.next()) |line| {
        try writer.print("\n    {s}", .{line});
    }
    try writer.writeAll(";\n");
}

fn renderCommonMethods(writer: *std.Io.Writer, widget_name: []const u8) !void {
    try writer.print("    pub fn create(window: Window) !*{s} {{\n", .{widget_name});
    try writer.writeAll("        const widget = try ashet.gui.create_widget(window, uuid);\n");
    try writer.writeAll("        return @ptrCast(widget);\n");
    try writer.writeAll("    }\n\n");

    try writer.print("    pub fn destroy(self: *{s}) void {{\n", .{widget_name});
    try writer.writeAll("        ashet.abi.resources.release(.from_ptr(self));\n");
    try writer.writeAll("    }\n\n");

    try writer.print("    pub fn eql(self: *{s}, widget: Widget) bool {{\n", .{widget_name});
    try writer.print("        const other: *{s} = @ptrCast(widget);\n", .{widget_name});
    try writer.writeAll("        return self == other;\n");
    try writer.writeAll("    }\n\n");

    try writer.print("    pub fn place(self: *{s}, rect: Rectangle) !Rectangle {{\n", .{widget_name});
    try writer.writeAll("        return try ashet.gui.place_widget(@ptrCast(self), rect);\n");
    try writer.writeAll("    }\n\n");

    try writer.print("    pub fn get_bounds(self: *{s}) !Rectangle {{\n", .{widget_name});
    try writer.writeAll("        return try ashet.gui.get_widget_bounds(@ptrCast(self));\n");
    try writer.writeAll("    }\n");
}

fn renderControlMethod(
    allocator: Allocator,
    writer: *std.Io.Writer,
    _: model.Document,
    widget: model.Widget,
    control: model.Message,
) !void {
    try writeDocComments(writer, "    ", control.docs);
    try writer.print("    pub fn {s}(self: *{s}", .{ control.name, widget.name });
    for (control.parameters) |parameter| {
        try writer.print(", {s}: {s}", .{ parameter.name, zigTypeName(parameter.type) });
    }

    if (control.return_type) |return_type| {
        try writer.print(") !{s} {{\n", .{zigTypeName(return_type)});
    } else {
        try writer.writeAll(") !void {\n");
    }

    if (control.return_type != null) {
        try writer.print(
            "        const result = try ashet.gui.control_widget(@ptrCast(self), {s}_msg, .{{\n",
            .{control.name},
        );
    } else {
        try writer.print(
            "        _ = try ashet.gui.control_widget(@ptrCast(self), {s}_msg, .{{\n",
            .{control.name},
        );
    }

    var slot_count: usize = 0;
    for (control.parameters) |parameter| {
        switch (parameter.type.raw_slot_width) {
            1 => {
                try writer.print("            usize_from_type({s}, {f}),\n", .{
                    zigTypeName(parameter.type),
                    std.zig.fmtId(parameter.name),
                });
                slot_count += 1;
            },
            2 => {
                try writer.print("            @intFromPtr({f}.ptr),\n", .{
                    std.zig.fmtId(parameter.name),
                });
                try writer.print("            {f}.len,\n", .{
                    std.zig.fmtId(parameter.name),
                });
                slot_count += 2;
            },
            else => unreachable,
        }
    }

    for (slot_count..4) |_| {
        try writer.print("            0,\n", .{});
    }

    try writer.writeAll("        });\n");

    if (control.return_type) |return_type| {
        try writer.print("        {s}\n", .{try returnExpr(allocator, widget, return_type)});
    }

    try writer.writeAll("    }\n");
}

fn slotExpr(
    allocator: Allocator,
    _: model.Widget,
    parameter: model.Parameter,
) ![]const u8 {
    switch (parameter.type.kind) {
        .builtin => switch (parameter.type.builtin.?) {
            .bool => return try std.fmt.allocPrint(allocator, "@as(usize, @intFromBool({s}))", .{parameter.name}),
            .i8, .i16, .i32 => return try std.fmt.allocPrint(
                allocator,
                "@bitCast(@as(isize, {s}))",
                .{parameter.name},
            ),
            .u8, .u16, .u32 => return try std.fmt.allocPrint(allocator, "@as(usize, {s})", .{parameter.name}),
            .isize => return try std.fmt.allocPrint(allocator, "@bitCast({s})", .{parameter.name}),
            .usize => return parameter.name,
            .contextptr => return try std.fmt.allocPrint(
                allocator,
                "@intFromPtr({s} orelse @ptrFromInt(0))",
                .{parameter.name},
            ),
            .framebuf => return try std.fmt.allocPrint(allocator, "@intFromPtr({s})", .{parameter.name}),
            .str, .strbuf => unreachable,
        },
        .named => return parameter.name,
    }
}

fn firstWideSlotExpr(allocator: Allocator, parameter: model.Parameter) ![]const u8 {
    return try std.fmt.allocPrint(allocator, "@intFromPtr({s}.ptr)", .{parameter.name});
}

fn secondWideSlotExpr(allocator: Allocator, parameter: model.Parameter) ![]const u8 {
    return try std.fmt.allocPrint(allocator, "{s}.len", .{parameter.name});
}

fn returnExpr(
    allocator: Allocator,
    _: model.Widget,
    return_type: model.TypeRef,
) ![]const u8 {
    switch (return_type.kind) {
        .builtin => switch (return_type.builtin.?) {
            .bool => return "return result != 0;",
            .i8 => return "return @bitCast(@as(u8, @truncate(result)));",
            .i16 => return "return @bitCast(@as(u16, @truncate(result)));",
            .i32 => return "return @bitCast(@as(u32, @truncate(result)));",
            .u8, .u16, .u32 => return "return @truncate(result);",
            .isize => return "return @bitCast(result);",
            .usize => return "return result;",
            .contextptr, .framebuf => return "return @ptrFromInt(result);",
            .str, .strbuf => @panic("malformed data"),
        },
        .named => return try std.fmt.allocPrint(
            allocator,
            "return undefined; // TODO: decode {s}",
            .{return_type.name},
        ),
    }
}

fn zigTypeName(type_ref: model.TypeRef) []const u8 {
    return switch (type_ref.kind) {
        .builtin => switch (type_ref.builtin.?) {
            .bool => "bool",
            .i8 => "i8",
            .i16 => "i16",
            .i32 => "i32",
            .u8 => "u8",
            .u16 => "u16",
            .u32 => "u32",
            .isize => "isize",
            .usize => "usize",
            .str => "[]const u8",
            .strbuf => "[]u8",
            .contextptr => "?*anyopaque",
            .framebuf => "Framebuffer",
        },
        .named => type_ref.name,
    };
}

fn writeDocComments(writer: *std.Io.Writer, indent: []const u8, docs: model.DocLines) !void {
    for (docs) |line| {
        if (line.len == 0) {
            try writer.print("{s}///\n", .{indent});
        } else {
            try writer.print("{s}/// {s}\n", .{ indent, line });
        }
    }
}
