//! This file is auto-generated by zpm-update and *should*
//! not be changed. This file can be checked into your VCS
//! and is able to work standalone.
const std = @import("std");

pub const pkgs = struct {
    pub const sdl = std.build.Pkg{
        .name = "sdl",
        .source = .{ .path = "vendor/sdl/src/binding/sdl.zig" },
    };
    pub const @"text-editor" = std.build.Pkg{
        .name = "text-editor",
        .source = .{ .path = "vendor/text-editor/src/TextEditor.zig" },
        .dependencies = &.{ziglyph},
    };
    pub const ziglyph = std.build.Pkg{
        .name = "ziglyph",
        .source = .{ .path = "vendor/ziglyph/src/ziglyph.zig" },
    };
};
pub const sdks = struct {
    pub const sdl = @import("vendor/sdl/Sdk.zig");
};
