const std = @import("std");
const model = @import("widget-def-model");

pub fn main() !u8 {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();

    const allocator = arena.allocator();
    const args = try std.process.argsAlloc(allocator);

    var input_path: ?[]const u8 = null;
    var output_path: ?[]const u8 = null;

    var index: usize = 1;
    while (index < args.len) : (index += 1) {
        const arg = args[index];
        if (std.mem.startsWith(u8, arg, "--output=")) {
            output_path = arg[9..];
            continue;
        }
        if (std.mem.eql(u8, arg, "--output")) {
            index += 1;
            if (index >= args.len) return usage();
            output_path = args[index];
            continue;
        }
        if (std.mem.startsWith(u8, arg, "-")) return usage();
        if (input_path != null) return usage();
        input_path = arg;
    }

    const resolved_input = input_path orelse return usage();
    const resolved_output = output_path orelse return usage();

    const source = try std.fs.cwd().readFileAlloc(allocator, resolved_input, 1 * 1024 * 1024);
    const parsed = try model.from_json_str(allocator, source);
    const document = parsed.value;

    var output_file = try std.fs.cwd().createFile(resolved_output, .{});
    defer output_file.close();

    var buffer: [1024]u8 = undefined;
    var file_writer = output_file.writer(&buffer);
    const writer = &file_writer.interface;

    try writer.writeAll(
        \\// Generated by widgets-codegen.
        \\// Loaded widget model successfully.
        \\
        \\const std = @import("std");
        \\const root = @import("standard-widgets");
        \\const ashet = @import("ashet");
        \\
        \\const Framebuffer = ashet.abi.Framebuffer;
        \\
        \\
    );

    for (document.widgets) |widget| {
        try writer.print(
            \\pub fn {[0]s}Dispatcher(comptime Impl: type) type {{
            \\    return struct {{
            \\        const logger = std.log.scoped(.@"widgets.{[0]s}");
            \\        const Data = ashet.gui.widgets.{[0]s};
            \\
            \\
        , .{widget.name});

        try writer.writeAll(
            \\        pub fn control(impl: *Impl, msg: ashet.gui.WidgetControlMessage) !usize {
            \\
        );

        if (widget.controls.len > 0) {
            try writer.writeAll(
                \\            switch(msg.type) {
                \\
            );

            for (widget.controls) |ctrl| {
                try writer.print(
                    \\             Data.{[0]s}_msg => {{
                    \\
                , .{ctrl.name});

                if (ctrl.return_type) |retval| {
                    try writer.print("return ashet.gui.usize_from_type({f}, ", .{
                        FmtDispatcherTypeRef{ .data = retval },
                    });
                }

                try writer.print("try impl.{[0]s}(", .{ctrl.name});

                var slot_index: usize = 0;
                for (ctrl.parameters) |param| {
                    switch (param.type.raw_slot_width) {
                        1 => {
                            try writer.print("ashet.gui.type_from_usize({f}, msg.params[{d}]),\n", .{
                                FmtDispatcherTypeRef{ .data = param.type },
                                slot_index,
                            });
                        },
                        2 => {
                            try writer.print("ashet.gui.type_from_usize({s}, msg.params[{d}])[0..msg.params[{d}]],\n", .{
                                zigTypeNameFirstPart(param.type),
                                slot_index + 0,
                                slot_index + 1,
                            });
                        },
                        else => unreachable,
                    }
                    slot_index += param.type.raw_slot_width;
                }

                try writer.writeAll(")");

                if (ctrl.return_type != null) {
                    try writer.writeAll(");\n");
                } else {
                    try writer.writeAll(";\nreturn 0;\n");
                }
                try writer.writeAll(
                    \\             },
                    \\
                );
            }
            try writer.writeAll(
                \\                else => {
                \\                    logger.warn("Unsupported control code: {}", .{msg.type});
                \\                    return 0;
                \\                },
                \\            }
                \\
            );
        } else {
            try writer.writeAll(
                \\            _ = impl;
                \\            logger.warn("Unsupported control code: {}", .{msg.type});
                \\            return 0;
                \\
            );
        }

        try writer.writeAll(
            \\        }
            \\
        );

        if (widget.events.len > 0) {
            try writer.writeAll(
                \\        pub fn notify_owner(impl: *Impl, event: Data.Event) !void {
                \\            const event_type, const args = event.marshal();
                \\            try ashet.gui.notify_owner(impl.wrapper().widget, event_type, args);
                \\        }
                \\
            );
        }

        try writer.writeAll(
            \\    };
            \\}
            \\
            \\
        );
    }
    try writer.flush();
    return 0;
}

fn usage() u8 {
    std.log.err("usage: widgets-codegen --output=<path> <input.json>", .{});
    return 1;
}

const FmtDispatcherTypeRef = std.fmt.Alt(model.TypeRef, formatFmtDispatcherTypeRef);

fn formatFmtDispatcherTypeRef(type_ref: model.TypeRef, writer: *std.Io.Writer) std.Io.Writer.Error!void {
    switch (type_ref.kind) {
        .builtin => try writer.writeAll(zigTypeName(type_ref)),
        .named => try writer.print("Impl.{f}", .{std.zig.fmtId(type_ref.name)}),
    }
}

fn zigTypeName(type_ref: model.TypeRef) []const u8 {
    return switch (type_ref.kind) {
        .builtin => switch (type_ref.builtin.?) {
            .bool => "bool",
            .i8 => "i8",
            .i16 => "i16",
            .i32 => "i32",
            .u8 => "u8",
            .u16 => "u16",
            .u32 => "u32",
            .isize => "isize",
            .usize => "usize",
            .str => "[]const u8",
            .strbuf => "[]u8",
            .contextptr => "?*anyopaque",
            .framebuf => "Framebuffer",
        },
        .named => type_ref.name,
    };
}

fn zigTypeNameFirstPart(type_ref: model.TypeRef) []const u8 {
    return switch (type_ref.kind) {
        .builtin => switch (type_ref.builtin.?) {
            .str => "[*]const u8",
            .strbuf => "[*]u8",

            .bool,
            .i8,
            .i16,
            .i32,
            .u8,
            .u16,
            .u32,
            .isize,
            .usize,
            .contextptr,
            .framebuf,
            => @panic("implementation bug"),
        },
        .named => type_ref.name,
    };
}
