name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        platform:
          - arm-ashet-vhc
          - arm-ashet-hc
          - arm-qemu-virt
          - rv32-qemu-virt
          - x86-hosted-linux
          - x86-pc-bios

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: "0.14.0"

      - name: Build ${{ matrix.platform }}
        run: |
          zig build ${{ matrix.platform }}

      - name: Upload disk image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: zig-out/${{ matrix.platform }}
          if-no-files-found: warn
          retention-days: 7
