name: Smoke Test

env:
  ZIG_VERSION: "0.15.2"
  ZIG_GLOBAL_CACHE_DIR: ${{ github.workspace }}/.zig-global-cache

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  smoketest:
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest]

        # Do not smoke-test "arm-ashet-hc", as it isn't runnable on a VM!
        platform:
          # - arm-ashet-vhc # TODO(fqu): VHC requires our own QEMU fork!
          - kernel: rv32-qemu-virt
            runner: rv32-qemu-virt
          - kernel: x86-hosted-linux
            runner: x86-hosted-linux
          - kernel: x86-pc-generic
            runner: x86-pc-generic-bios
          # TODO: Enable UEFI runner when q35/SATA works!
          # - kernel: x86-pc-generic
          #   runner: x86-pc-generic-uefi

        optimize_kernel:
          - false
          - true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Cache Zig package cache
        uses: actions/cache@v4
        with:
          # Zig stores downloaded packages in the p subdirectory of the global cache.
          path: ${{ env.ZIG_GLOBAL_CACHE_DIR }}/p
          key: zig-pkg-cache-${{ env.ZIG_VERSION }}-${{ hashFiles('**/build.zig.zon') }}
          restore-keys: |
            zig-pkg-cache-${{ env.ZIG_VERSION }}-
          enableCrossOsArchive: true

      - name: Install QEMU
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: qemu-system
          version: 1.1

      - name: Build ${{ matrix.platform.kernel }}
        run: |
          zig build -Doptimize-kernel=${{ matrix.optimize_kernel }} ${{ matrix.platform.kernel }}

      - name: Perform Smoke Test ${{ matrix.platform.runner }}
        run: |
          zig build -Doptimize-kernel=${{ matrix.optimize_kernel }} -Dmachine=${{ matrix.platform.runner }} -Dgui=headless install

          # this command is allowed to fail, we're doing checks by grep.
          timeout 20s zig build -Doptimize-kernel=${{ matrix.optimize_kernel }} -Dmachine=${{ matrix.platform.runner }} -Dgui=headless run 2>&1 | tee kernel.log || true

          # Test if the desktop application did start:
          if ! grep -F "classic desktop ready!" kernel.log; then
            echo "kernel failed to start desktop application!" 1>&2
            false
          fi

          # Test that we didn't panic:
          if grep -Fi "Panic:" kernel.log; then
            # fail!
            echo "kernel had a panic!" 1>&2
            false
          fi
