name: Smoke Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  smoketest:
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest]

        # Do not smoke-test "arm-ashet-hc", as it isn't runnable on a VM!
        platform:
          # - arm-ashet-vhc # TODO(fqu): VHC requires our own QEMU fork!
          - rv32-qemu-virt
          - x86-hosted-linux
          - x86-pc-bios

        optimize_kernel:
          - false
          - true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: "0.14.0"

      - name: Install QEMU
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: qemu-system
          version: 1.1

      - name: Build ${{ matrix.platform }}
        run: |
          zig build -Doptimize-kernel=${{ matrix.optimize_kernel }} ${{ matrix.platform }}

      - name: Perform Smoke Test ${{ matrix.platform }}
        run: |
          zig build -Doptimize-kernel=${{ matrix.optimize_kernel }} -Dmachine=${{ matrix.platform }} -Dgui=headless install

          # this command is allowed to fail, we're doing checks by grep.
          timeout 20s zig build -Doptimize-kernel=${{ matrix.optimize_kernel }} -Dmachine=${{ matrix.platform }} -Dgui=headless run 2>&1 | tee kernel.log || true

          # Test if the desktop application did start:
          if ! grep -F "classic desktop ready!" kernel.log; then
            echo "kernel failed to start desktop application!" 1>&2
            false
          fi

          # Test that we didn't panic:
          if grep -Fi "Panic:" kernel.log; then
            # fail!
            echo "kernel had a panic!" 1>&2
            false
          fi
